### PR TITLE
Refactor/Add docs bump to 2.0.0

### PR DESCRIPTION
**Pull request by leshow**
Great project! I had made a bunch of changes to the original source, the same basic structure is there but I removed some dependencies and wrote the code in a style I was more comfortable with. 

I figured it couldn't hurt to submit a PR and see if you wanted these changes, however since it does change the external types quite a bit, based on preference more than anything else, feel free to just close this if you don't want to accept!

### CODE REVIEW

**Comment by LinkTed** [comment]
Thanks for your support. I did not have time to examine the whole contribution and details of your code, but it looks great at the first glance. Could you comment in this PR that the contribution and any other future contributions will be licensed under the projects license for the present and future? For example, add the following statement: 
```
I'm hereby licensing my contribution and any future contributions under the projects license for the present and future.
```
To ensure that there will be no license problems with your contribution in the future.

**Comment by leshow** [comment]
Yes, sure. The code works pretty well and passes your unit test suite so I'm fairly confident in it.

I'm hereby licensing my contribution and any future contributions under the projects license for the present and future.

**Comment by LinkTed** [comment]
The code looks awesome, many improvements. Did you remove the `num-trait` to reduce the dependencies or is there any other reason?

I only have two suggestions:
1. Could you rename `EncodeErr` and `DecodeErr` to `EncodeError` and `DecodeError`?
2. Could you rename `DOH` struct to `DnsOverHttps`?

Again thank you for your awesome work.

**Comment by leshow** [comment]
Sure! We can of course rename the error type back to what it was before. I actually forgot about that change, of course you want to maintain the same external error type name for the library API.

I'm cool with renaming the DOH struct also.

I removed num-trait to make the dependency list smaller and because there was a way to do it with std & `repr`. Again that's more of a preference thing I guess it just seemed like trading 2 dependencies for a dozen or so lines of code was a good idea.

**Comment by LinkTed** [comment]
Thanks

**Pull request merged**
